<a href="https://colab.research.google.com/github/Akbarbfn/Desain-Analis-Dan-Algoritma/blob/main/Pertemuan_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [84]:
import numpy as np

In [ ]:
aList = ["John", 33, "Toronto", True]
print(aList)

['John', 33, 'Toronto', True]


In [6]:
Mahasiswa = ["Akbar Bafunazair", 2018071013, "Informatika","Desain Analisis Algoritma", "15 September 2021" ,"Universitas Pembangunan Jaya"]
Mahasiswa[1]

'Green'

In [9]:
Mahasiswa = ["Akbar Bafunazair", 2018071013, "Informatika","Desain Analisis Algoritma", "15 September 2021" ,"Universitas Pembangunan Jaya"]
Mahasiswa[5]

'Universitas Pembangunan Jaya'

In [13]:
bin_colors = ['Red','Green','Blue','Yellow']
bin_colors[0:2]

['Red', 'Green']

In [ ]:
Mahasiswa = ["Akbar Bafunazair", "2018071013", "Informatika","Desain Analisis Algoritma", "15 September 2021" ,"Universitas Pembangunan Jaya"]
Mahasiswa[1:6]

In [21]:
bin_colors=['Red','Green','Blue','Yellow']
for aColor in bin_colors:
  print(aColor + " Square")

Red Square
Green Square
Blue Square
Yellow Square


In [19]:
aList = ["Akbar Bafunazair", "2018071013", "Informatika","Desain Analisis Algoritma", "15 September 2021" ,"Universitas Pembangunan Jaya"]
for tampilan in aList:
  print("UPJ " + tampilan)

UPJ Akbar Bafunazair
UPJ 2018071013
UPJ Informatika
UPJ Desain Analisis Algoritma
UPJ 15 September 2021
UPJ Universitas Pembangunan Jaya


In [23]:
bin_colors=('Red','Green','Blue','Yellow')
bin_colors[1]

'Green'

In [24]:
bin_colors[1:]

('Green', 'Blue', 'Yellow')

In [25]:
UPJ = ("Universitas", "Pembangunan","Jaya")
UPJ[0:]

('Universitas', 'Pembangunan', 'Jaya')

In [31]:
tuple1 = 400
tuple2 = 200,400,600
tuple3 = 300
tuple4 = 400,800

print ("Pertama : ") 
print(tuple1)
print ("Kedua :")
print(tuple2)
print ("Ketiga : " )
print(tuple3)
print ("Keempat : " )
print(tuple4)

Pertama : 
400
Kedua :
(200, 400, 600)
Ketiga : 
300
Keempat : 
(400, 800)


In [27]:
tuple =([400],[200,400,600],[300],[400,800],"Angka")
tuple[0:]

([400], [200, 400, 600], [300], [400, 800], 'Angka')

In [28]:
bin_colors ={
    "manual_color":"Yellow",
    "approved_color":"Green",
    "refused_color":"Red"
}

print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [33]:
bin_colors.get('approved_color')

'Green'

In [34]:
bin_colors['approved_color']

'Green'

In [36]:
bin_colors['approved_color']="White"

print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'White', 'refused_color': 'Red'}


In [40]:
Mahasiswa ={
    "Nama":"Akbar Bafunazair",
    "NIM" :"2018071013",
    "Prodi" : "Informatika",
    "Universitas" : "Universitas Pembangunan Jaya"
}
print(Mahasiswa)

{'Nama': 'Akbar Bafunazair', 'NIM': '2018071013', 'Prodi': 'Informatika', 'Universitas': 'Universitas Pembangunan Jaya'}


In [51]:
green = {'Grass','leaves'}
print(green)

{'leaves', 'Grass'}


In [60]:
green = {'Leaves','Grass','Grass'}
print(green)

{'Leaves', 'Grass'}


In [61]:
yellow = {'dandelions','fire hydrant','leaves'}
red = {'fire hydrant','rose','blood','leaves'}
print(yellow | red)
print(yellow & red)

{'rose', 'fire hydrant', 'leaves', 'blood', 'dandelions'}
{'leaves', 'fire hydrant'}


In [64]:
import pandas as pd

df=pd.DataFrame([
  ['1','Fares',32,True],
  ['2','Elena',23,False],
  ['3','Steven',40,True]])

In [65]:
df.columns = ['id','name','age','decision']
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [66]:
df[['name','age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [67]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [80]:
mahasiswa=pd.DataFrame([
  ['1','Informatika',50 ,30 ,20,],
  ['2','Sistem Informasi',55 ,30 ,25,],
  ['3','Teknik Sipil',40 ,30 ,10,]])

In [83]:
mahasiswa.column = ['Prodi','Mahasiswa','Laki - Laki','Perempuan']
mahasiswa

0                 1   2   3   4
0  1       Informatika  50  30  20
1  2  Sistem Informasi  55  30  25
2  3      Teknik Sipil  40  30  10

In [85]:
myMatrix = np.array([[11,12,13],[21,22,23],[31,32,33]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [88]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [89]:
myMatrix = np.array([[100,200,300],[700,600,500],[900,1000,800]])
print(myMatrix)

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]


In [94]:
class Stack:
    def __init__(self):
        self.items=[]
    def isEmpty(self):
        return self.items==[]
    def push(self,item):
        self.items.append(item)
    def pop(self):
        return self.items.pop()
    def peek(self):
        return self.items[len(self.items0)-l]
    def size(self):
        return len(self.items)
stack=Stack()
stack.push('Red')
stack.push('Green')
stack.push('Blue')
stack.push('Yellow')
print(stack.pop())
print(stack.isEmpty())

Yellow
False


In [93]:
class Queue(object):
  def __init__(self):
    self.items =[]
  def isEmpty(self):
    return self.items == []
  def enqueue(self, item):
    self.items.insert(0,item)
  def dequeue(self):
    return self.items.pop()
  def size(self):
    return len(self.items)

queue = Queue()
queue.enqueue('Red')
queue.enqueue('Green')
queue.enqueue('Blue')
queue.enqueue('Yellow')

print(queue.size())

4
